window.GG24_DATA = {
  generatedAt: '2026-06-13T00:00:00.000+09:00',
  source: {
    name: '공공데이터포털 정책 데이터 샘플',
    provider: '공공데이터포털',
    url: 'https://www.data.go.kr/data/15113968/openapi.do',
    note: '전체 데이터는 tools/update-gov24-data.mjs로 다시 생성합니다.',
  },
  policies: [
    {
      id: 'sample-earned-income-tax-credit',
      title: '근로장려금 신청 안내',
      type: '지원금',
      institution: '국세청',
      deadline: '상시 또는 정기 신청',
      views: 52000,
      maxBenefit: '가구 유형별 차등',
      region: '전국',
      income: '소득·재산 기준 확인',
      target: '근로소득, 사업소득, 종교인소득이 있는 저소득 가구',
      method: '홈택스 또는 손택스에서 신청',
      summary: '일하는 저소득 가구의 근로를 장려하고 실질소득을 지원하는 제도입니다.',
      tags: ['지원금', '전국', '저소득층'],
      sourceUrl: 'https://www.hometax.go.kr/',
      featured: true,
    },
    {
      id: 'sample-unclaimed-refund',
      title: '정부24 미환급금 찾기',
      type: '환급금',
      institution: '행정안전부',
      deadline: '상시',
      views: 49000,
      maxBenefit: '미환급금 조회',
      region: '전국',
      income: '무관',
      target: '국세, 지방세, 보관금 등 미환급금 여부를 확인하려는 국민',
      method: '정부24 미환급금 찾기 서비스에서 본인 확인 후 조회',
      summary: '각 기관에 흩어진 미환급금 조회 경로를 한 번에 확인할 수 있는 서비스입니다.',
      tags: ['환급금', '정부24', '전국'],
      sourceUrl: 'https://www.gov.kr/portal/service/serviceInfo/174100000054',
      featured: true,
    },
    {
      id: 'sample-housing-loan',
      title: '주택도시기금 전세자금 대출',
      type: '대출',
      institution: '주택도시보증공사',
      deadline: '상시',
      views: 39000,
      maxBenefit: '상품별 상이',
      region: '전국',
      income: '상품별 기준',
      target: '전세자금, 주택자금 등 주거 금융이 필요한 청년·신혼부부',
      method: '기금e든든에서 자격 확인 후 신청',
      summary: '버팀목 전세자금, 디딤돌대출 등 주거 금융 상품을 확인할 수 있습니다.',
      tags: ['대출', '주거', '청년', '신혼부부'],
      sourceUrl: 'https://enhuf.molit.go.kr/',
      featured: true,
    },
    {
      id: 'sample-seoul-youth-rent',
      title: '서울 청년월세 지원',
      type: '지원금',
      institution: '서울특별시',
      deadline: '공고 확인',
      views: 28100,
      maxBenefit: '월세 일부 지원',
      region: '서울',
      income: '소득 기준 확인',
      target: '서울 거주 청년 1인 가구 또는 주거비 부담 청년',
      method: '서울시 청년정책 포털 공고 확인 후 신청',
      summary: '청년층의 주거비 부담을 낮추기 위해 월세 일부를 지원하는 사업입니다.',
      tags: ['지원금', '서울', '청년', '주거'],
      sourceUrl: 'https://youth.seoul.go.kr/',
      featured: true,
    },
    {
      id: 'sample-gyeongnam-veterans',
      title: '경남 국가유공자 보훈수당',
      type: '지원금',
      institution: '경상남도',
      deadline: '상시 또는 지자체 문의',
      views: 17800,
      maxBenefit: '수당 지급',
      region: '경남',
      income: '지자체 기준',
      target: '국가유공자, 보훈대상자, 참전유공자와 유족',
      method: '주소지 읍면동 행정복지센터 문의',
      summary: '국가를 위해 헌신한 보훈대상자의 예우를 위해 지자체 기준에 따라 수당을 지급합니다.',
      tags: ['지원금', '경남', '국가유공자·보훈'],
      sourceUrl: 'https://www.gyeongnam.go.kr/',
      featured: true,
    },
    {
      id: 'sample-taean-local-support',
      title: '태안군 주민 생활안정 지원사업',
      type: '지원금',
      institution: '태안군',
      deadline: '공고 확인',
      views: 8200,
      maxBenefit: '사업별 상이',
      region: '충남',
      income: '사업별 기준',
      target: '태안군 거주 주민, 저소득층, 취약계층',
      method: '태안군청 공고 또는 읍면 행정복지센터 확인',
      summary: '태안 지역 주민을 대상으로 생활안정, 복지, 취업 관련 지원 정보를 확인할 수 있습니다.',
      tags: ['지원금', '충남', '태안', '저소득층'],
      sourceUrl: 'https://www.taean.go.kr/',
      featured: false,
    },
    {
      id: 'sample-smallbiz-policy-loan',
      title: '소상공인 정책자금',
      type: '대출',
      institution: '소상공인시장진흥공단',
      deadline: '예산 소진 시',
      views: 36000,
      maxBenefit: '상품별 상이',
      region: '전국',
      income: '사업자 요건',
      target: '정책자금 지원 요건을 충족하는 소상공인, 자영업자',
      method: '소상공인정책자금 홈페이지에서 온라인 접수',
      summary: '운영자금, 성장기반자금 등 소상공인을 위한 정책 대출 접수 정보를 확인할 수 있습니다.',
      tags: ['대출', '소상공인', '전국'],
      sourceUrl: 'https://ols.semas.or.kr/',
      featured: false,
    },
    {
      id: 'sample-agriculture-direct-payment',
      title: '농업인 공익직불금',
      type: '지원금',
      institution: '농림축산식품부',
      deadline: '공고 확인',
      views: 23000,
      maxBenefit: '경작 요건별 지급',
      region: '전국',
      income: '농업경영체 기준',
      target: '농업경영체 등록 농업인과 농가',
      method: '농지 소재지 읍면동 또는 온라인 신청 공고 확인',
      summary: '농업·농촌의 공익 기능 증진을 위해 요건을 충족하는 농업인에게 지급하는 제도입니다.',
      tags: ['지원금', '농어업인', '전국'],
      sourceUrl: 'https://www.mafra.go.kr/',
      featured: false,
    },
  ],
};
